🔧 Fix: add x86 ubuntu support for Prisma client
PrismaClientInitializationError: Prisma Client could not locate the Query Engine for runtime "linux-musl-openssl-3.0.x".

This happened because Prisma Client was generated for "darwin-arm64", but the actual deployment required "linux-musl-openssl-3.0.x".
Add "linux-musl-openssl-3.0.x" to `binaryTargets` in the "schema.prisma" file and run `prisma generate` after saving it:

해당 오류로 인해서 Prisma schema 파일의 binaryTargets에 옵션 추가